## Home Price Prediction

## Project Description:

In this particular project, we are using a dataset that contains information like, Address, Rooms, Type, Price, Seller etc and using that to predict the price of a given house. 
However, before you go ahead and make a prediction, it is advised that you first pre-process the data, since it may contain some irregularities and noise. In addition, try various tricks and techniques in order to gain the best accuracy in your predictions.

## Objective
To build a machine learning model that predicts house prices based on key features and helps understand factors influencing property valuation.

## Data Loading
In this step, the dataset is loaded into the environment for further analysis. 
The dataset contains information about different properties, including their features and corresponding prices.

In [3]:
# Import required libraries for data analysis and machine learning
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# Load dataset
data = pd.read_csv(r"C:\Users\ritus\Downloads\ML Linear Regression Home Price Prediction & Analysis Project  Resource16932049360 (1).txt")

# Display the data 
data

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,03/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,03/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,04/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,04/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,04/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,13 Burns St,4,h,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,Yarraville,29A Murray St,2,h,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,Yarraville,147A Severn St,2,t,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34855,Yarraville,12/37 Stephen St,3,h,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

## Data Understanding
Before performing any analysis, it is important to understand the structure and characteristics of the dataset. This includes checking the number of rows and columns, data types, and summary statistics of numerical features.
This step helps in identifying potential issues such as missing values, incorrect data types, and outliers.

In [5]:
data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Address        34857 non-null  object
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  object
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  object
 6   SellerG        34857 non-null  object
 7   Date           34857 non-null  object
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       26640 non-null  float64
 11  Bathroom       26631 non-null  float64
 12  Car            26129 non-null  float64
 13  Landsize       23047 non-null  float64
 14  BuildingArea   13742 non-null  float64
 15  YearBuilt      15551 non-null  float64
 16  CouncilArea    34854 non-null  object
 17  Lattitude      26881 non-null  float64
 18  Longtitude     26881 non-null  float64
 19  Regionname     34854 non-null  object
 20  Propertycount  34854 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 5.6+ MB

In [7]:
data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,34857.000000,2.724700e+04,34856.000000,34856.000000,26640.000000,26631.000000,26129.000000,23047.000000,13742.00000,15551.000000,26881.000000,26881.000000,34854.000000
mean,3.031012,1.050173e+06,11.184929,3116.062859,3.084647,1.624798,1.728845,593.598993,160.25640,1965.289885,-37.810634,145.001851,7572.888306
std,0.969933,6.414671e+05,6.788892,109.023903,0.980690,0.724212,1.010771,3398.841946,401.26706,37.328178,0.090279,0.120169,4428.090313
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1196.000000,-38.190430,144.423790,83.000000
25%,2.000000,6.350000e+05,6.400000,3051.000000,2.000000,1.000000,1.000000,224.000000,102.00000,1940.000000,-37.862950,144.933500,4385.000000
50%,3.000000,8.700000e+05,10.300000,3103.000000,3.000000,2.000000,2.000000,521.000000,136.00000,1970.000000,-37.807600,145.007800,6763.000000
75%,4.000000,1.295000e+06,14.000000,3156.000000,4.000000,2.000000,2.000000,670.000000,188.00000,2000.000000,-37.754100,145.071900,10412.000000
max,16.000000,1.120000e+07,48.100000,3978.000000,30.000000,12.000000,26.000000,433014.000000,44515.00000,2106.000000,-37.390200,145.526350,21650.000000

## Data Cleaning
Data cleaning is a crucial step to ensure the dataset is accurate and suitable for analysis and modeling. In this step:

- Missing values are identified and handled appropriately  
- Duplicate records are removed  
- Inconsistent or incorrect data entries are corrected  

Proper data cleaning improves the quality of the dataset and enhances model performance.

In [8]:
# Drop the columns that are not required for the analysis or not affect your targeted column 
data.drop(["Address", "Date", "Postcode", "YearBuilt", "Lattitude", "Longtitude"],axis = 1, inplace = True)

In [9]:
data

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.0,79.0,Yarra City Council,Northern Metropolitan,4019.0
3,Abbotsford,3,u,NaN,VB,Rounds,2.5,3.0,2.0,1.0,0.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.0,150.0,Yarra City Council,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,1480000.0,PI,Jas,6.3,4.0,1.0,3.0,593.0,NaN,Maribyrnong City Council,Western Metropolitan,6543.0
34853,Yarraville,2,h,888000.0,SP,Sweeney,6.3,2.0,2.0,1.0,98.0,104.0,Maribyrnong City Council,Western Metropolitan,6543.0
34854,Yarraville,2,t,705000.0,S,Jas,6.3,2.0,1.0,2.0,220.0,120.0,Maribyrnong City Council,Western Metropolitan,6543.0
34855,Yarraville,3,h,1140000.0,SP,hockingstuart,6.3,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,Western Metropolitan,6543.0
34856,Yarraville,2,h,1020000.0,PI,RW,6.3,2.0,1.0,0.0,250.0,103.0,Maribyrnong City Council,Western Metropolitan,6543.0

In [10]:
# Check missing values
data.isnull().sum()

Suburb               0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Distance             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
CouncilArea          3
Regionname           3
Propertycount        3
dtype: int64

In [11]:
data.columns

Index(['Suburb', 'Rooms', 'Type', 'Price', 'Method', 'SellerG', 'Distance',
       'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea',
       'CouncilArea', 'Regionname', 'Propertycount'],
      dtype='object')

In [12]:
# Fill missing values
data[['Distance','Bedroom2', 'Bathroom', 'Car','Propertycount']] = data[['Distance','Bedroom2', 'Bathroom', 'Car','Propertycount']].fillna(0)

In [13]:
data

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.0,79.0,Yarra City Council,Northern Metropolitan,4019.0
3,Abbotsford,3,u,NaN,VB,Rounds,2.5,3.0,2.0,1.0,0.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.0,150.0,Yarra City Council,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,1480000.0,PI,Jas,6.3,4.0,1.0,3.0,593.0,NaN,Maribyrnong City Council,Western Metropolitan,6543.0
34853,Yarraville,2,h,888000.0,SP,Sweeney,6.3,2.0,2.0,1.0,98.0,104.0,Maribyrnong City Council,Western Metropolitan,6543.0
34854,Yarraville,2,t,705000.0,S,Jas,6.3,2.0,1.0,2.0,220.0,120.0,Maribyrnong City Council,Western Metropolitan,6543.0
34855,Yarraville,3,h,1140000.0,SP,hockingstuart,6.3,0.0,0.0,0.0,NaN,NaN,Maribyrnong City Council,Western Metropolitan,6543.0
34856,Yarraville,2,h,1020000.0,PI,RW,6.3,2.0,1.0,0.0,250.0,103.0,Maribyrnong City Council,Western Metropolitan,6543.0

In [22]:
# Fill missing values
data['Landsize'] = data['Landsize'].fillna(data.Landsize.mean())
data['BuildingArea'] = data['BuildingArea'].fillna(data.BuildingArea.mean())

In [23]:
data

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.000000,79.0000,Yarra City Council,Northern Metropolitan,4019.0
3,Abbotsford,3,u,NaN,VB,Rounds,2.5,3.0,2.0,1.0,0.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.000000,150.0000,Yarra City Council,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,1480000.0,PI,Jas,6.3,4.0,1.0,3.0,593.000000,160.2564,Maribyrnong City Council,Western Metropolitan,6543.0
34853,Yarraville,2,h,888000.0,SP,Sweeney,6.3,2.0,2.0,1.0,98.000000,104.0000,Maribyrnong City Council,Western Metropolitan,6543.0
34854,Yarraville,2,t,705000.0,S,Jas,6.3,2.0,1.0,2.0,220.000000,120.0000,Maribyrnong City Council,Western Metropolitan,6543.0
34855,Yarraville,3,h,1140000.0,SP,hockingstuart,6.3,0.0,0.0,0.0,593.598993,160.2564,Maribyrnong City Council,Western Metropolitan,6543.0
34856,Yarraville,2,h,1020000.0,PI,RW,6.3,2.0,1.0,0.0,250.000000,103.0000,Maribyrnong City Council,Western Metropolitan,6543.0

In [25]:
# Drop null values 
data.dropna(inplace = True)

In [26]:
# Recheck the null values 
data.isnull().sum()

Suburb           0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Distance         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
CouncilArea      0
Regionname       0
Propertycount    0
dtype: int64

In [27]:
# check the shape of the data so it get changea as per our need 
data.shape

(27244, 15)

## Exploratory Data Analysis (EDA)

Exploratory Data Analysis is performed to understand the relationships between different variables and identify patterns in the data.

This includes:
- Analyzing distribution of house prices  
- Studying relationship between area and price  
- Identifying key features influencing house prices  

EDA helps in gaining insights and guiding feature selection for model building.

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27244 entries, 1 to 34856
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         27244 non-null  object
 1   Rooms          27244 non-null  int64
 2   Type           27244 non-null  object
 3   Price          27244 non-null  float64
 4   Method         27244 non-null  object
 5   SellerG        27244 non-null  object
 6   Distance       27244 non-null  float64
 7   Bedroom2       27244 non-null  float64
 8   Bathroom       27244 non-null  float64
 9   Car            27244 non-null  float64
 10  Landsize       27244 non-null  float64
 11  BuildingArea   27244 non-null  float64
 12  CouncilArea    27244 non-null  object
 13  Regionname     27244 non-null  object
 14  Propertycount  27244 non-null  float64
dtypes: float64(8), int64(1), object(6)
memory usage: 3.3+ MB

In [29]:
data['Method'].unique()

array(['S', 'SP', 'PI', 'VB', 'SA'], dtype=object)

In [30]:
data['SellerG'].unique()

array(['Biggin', 'Nelson', 'Jellis', 'Dingle', 'Purplebricks', 'Greg',
       'LITTLE', 'Collins', 'Kay', 'Beller', 'Marshall', 'hockingstuart',
       'Brad', 'Maddison', 'Barry', 'Airport', 'Considine', 'Rendina',
       'Ray', 'Propertyau', 'McDonald', 'Frank', 'Prof.', 'Harcourts',
       'Thomson', 'Buxton', 'RT', "Sotheby's", 'Cayzer', 'Chisholm',
       'Brace', 'Miles', 'Holland', 'McGrath', 'Love', 'Thomas', 'Barlow',
       'Sweeney', 'Village', 'Jas', 'Williams', 'Gunn&Co', 'Burnham',
       'Compton', 'FN', 'Hunter', 'Raine&Horne', 'Noel', 'Hodges', 'Gary',
       'Fletchers', 'Woodards', 'Raine', 'Alexkarbon', 'Walshe', 'Weda',
       'Stockdale', 'Tim', 'AIME', 'Moonee', 'HAR', 'Edward', 'Philip',
       'RW', 'North', 'MICM', 'Ascend', 'Christopher', 'Morrison',
       'Mandy', 'R&H', 'Fletchers/One', 'Lindellas', 'Appleby', 'Assisi',
       'One', 'Owen', 'Parkes', 'C21', "O'Brien", 'Bayside', 'Paul',
       'hockingstuart/Buxton', 'First', 'Matthew', 'Melbourne',
       'Anderson', 'Nick', 'Allens', 'Bells', 'Trimson', 'Douglas',
       'Batty', 'GL', 'YPA', "Tiernan's", 'J', 'Rodney', 'Joseph',
       'Harrington', 'Galldon', 'Chambers', 'Peter', 'Grantham',
       'hockingstuart/Advantage', 'Garvey', "O'Donoghues", 'Hamilton',
       'Bekdon', 'Ross', 'Weast', 'Century', 'Kelly', 'Property',
       "Private/Tiernan's", 'Australian', 'Bustin', "Abercromby's",
       'Castran', 'iTRAK', 'Del', 'Nicholson', 'JMRE', 'ASL', 'Re', 'RE',
       'Ham', 'Darren', 'Vic', 'Scott', 'Pride', 'Morleys', 'Wilson',
       'Buxton/Advantage', 'Whiting', 'Pagan', 'Joe', 'Red', 'Caine',
       'Naison', 'Sweeney/Advantage', 'Nguyen', 'Domain', 'Eview',
       'Jason', 'Professionals', "D'Aprano", 'Charlton', 'CASTRAN',
       'Wood', 'Haughton', 'William', 'Coventry', 'Buckingham',
       'Nardella', 'Reach', 'Walsh', 'Karen', 'LJ', 'Direct',
       'Fletchers/Fletchers', 'Besser', 'Johnston', 'Redina', 'Clairmont',
       'Changing', 'Lucas', 'Elite', 'Buxton/Find', 'W.B.', 'Leased',
       'Win', 'New', 'Geoff', 'hockingstuart/Barry', 'Blue', 'Steveway',
       'Dixon', 'Parkinson', 'VICPROP', 'Meadows', 'Allan', 'S&L',
       'Crane', 'Calder', 'Homes', 'Zahn', 'Mason', 'David', 'Luxe',
       'Prowse', 'Ken', 'iOne', 'hockingstuart/Village', 'Iconek',
       'Luxton', 'Hooper', 'Oak', 'White', 'Weston', 'Reed', 'Oriental',
       'Craig', 'Max', 'Rosin', 'Steller', 'Real', 'Hall', 'Icon',
       'buyMyplace', 'Collings', 'WHITEFOX', 'Metro', '@Realty',
       'Hoskins', 'Gardiner', 'McLennan', 'Triwest', 'PRDNationwide',
       'Only', 'Leyton', 'Obrien', 'Maitland', 'Reliance', 'Rounds',
       'Millership', 'iSell', 'L', 'Ash', 'Jim', 'Ace', 'Flannagan',
       'JRW', 'Carter', 'M.J', 'iProperty', 'Hayeswinckle', 'Schroeder',
       'iHomes', 'VICProp', 'REMAX', 'Space', 'Victory', 'Aumeca',
       'Smart', 'Mindacom', 'Ryder', 'Asset', 'LLC', 'Sell', 'Mitchell',
       'U', 'Nicholas', 'Keatings', 'Aquire', 'Conquest', 'Rombotis',
       'Prime', 'Donovan', 'Community', 'Free', 'Veitch', 'Peake',
       'Ristic', 'Upper', 'Daniel', 'Xynergy', 'VicHomes', 'Westside',
       'Leeburn', 'TRUE', 'Leading', 'Bullen', 'Better', 'Langwell',
       'Kaye', 'Nicholls', 'Bowman', 'Boutique', 'Just', 'Home',
       'McNaughton', 'Black', 'The', 'Open', 'Darras', 'Roger', 'Follett',
       'Le', 'McEwing', 'Sandhurst', 'Avion', 'Boran',
       'hockingstuart/hockingstuart', 'Area', 'MJ', 'Eric', 'SN', 'P',
       'PRD', 'Bombay', 'Quinta', 'T', 'Rexhepi', 'Point', 'LJH', 'Munn',
       'Justin', 'Blackbird', 'Sweeney/Burnham', 'H', 'Branon', 'Alex',
       'Benchmark', 'Gellibrand', 'hockingstuart/Harcourts', 'Charter',
       'Surreal', 'Upside', 'OBrien', 'Meallin', 'JY', 'Mark', 'For',
       'Leaders', 'Shape', 'McGrath/Langwell', 'Benlor', 'Burns',
       'K.R.Peters', 'Buxton/Buxton', 'Buxton/Marshall', 'CarlinSmith',
       'hockingstuart/Sweeney', 'People', 'hockingstuart/Biggin', 'Mega',
       'Skad', 'Wyndham', 'Create', 'Janice', 'G&H', 'Commercial', 'PSP',
       'Unity', 'hockingstuart/Marshall', 'McGrath/First', 'Spencer',
       'Sanctuary'], dtype=object)

In [32]:
data['CouncilArea'].unique()

array(['Yarra City Council', 'Moonee Valley City Council',
       'Port Phillip City Council', 'Darebin City Council',
       'Hobsons Bay City Council', 'Stonnington City Council',
       'Boroondara City Council', 'Monash City Council',
       'Glen Eira City Council', 'Whitehorse City Council',
       'Maribyrnong City Council', 'Bayside City Council',
       'Moreland City Council', 'Manningham City Council',
       'Melbourne City Council', 'Banyule City Council',
       'Brimbank City Council', 'Kingston City Council',
       'Hume City Council', 'Knox City Council', 'Maroondah City Council',
       'Casey City Council', 'Melton City Council',
       'Greater Dandenong City Council', 'Nillumbik Shire Council',
       'Whittlesea City Council', 'Frankston City Council',
       'Macedon Ranges Shire Council', 'Yarra Ranges Shire Council',
       'Wyndham City Council', 'Cardinia Shire Council',
       'Moorabool Shire Council', 'Mitchell Shire Council'], dtype=object)

In [34]:
data['Regionname'].unique()

array(['Northern Metropolitan', 'Western Metropolitan',
       'Southern Metropolitan', 'Eastern Metropolitan',
       'South-Eastern Metropolitan', 'Eastern Victoria',
       'Northern Victoria', 'Western Victoria'], dtype=object)

## Feature Engineering

Feature engineering involves transforming raw data into meaningful features that improve model performance.

In this step:
- Categorical variables are converted into numerical format  
- Irrelevant features are removed  
- Important features are selected for modeling  

This step ensures that the data is suitable for machine learning algorithms.

In [35]:
# Convert categorical variables into numerical
data = pd.get_dummies(data, drop_first = True)

In [36]:
data.shape

(27244, 745)

In [37]:
data.head()

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Propertycount,Suburb_Aberfeldie,...,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
1,2,1480000.0,2.5,2.0,1.0,1.0,202.0,160.2564,4019.0,False,...,False,True,False,False,True,False,False,False,False,False
2,2,1035000.0,2.5,2.0,1.0,0.0,156.0,79.0000,4019.0,False,...,False,True,False,False,True,False,False,False,False,False
4,3,1465000.0,2.5,3.0,2.0,0.0,134.0,150.0000,4019.0,False,...,False,True,False,False,True,False,False,False,False,False
5,3,850000.0,2.5,3.0,2.0,1.0,94.0,160.2564,4019.0,False,...,False,True,False,False,True,False,False,False,False,False
6,4,1600000.0,2.5,3.0,1.0,2.0,120.0,142.0000,4019.0,False,...,False,True,False,False,True,False,False,False,False,False

## Model Building

In this step, a machine learning model is built to predict house prices.

Linear Regression is used as the baseline model due to its simplicity and effectiveness for regression problems.

The dataset is split into training and testing sets to evaluate model performance on unseen data.

In [38]:
# Define features and target
x = data.drop('Price', axis = 1)
y = data['Price']

In [40]:
x.head()

,Rooms,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Propertycount,Suburb_Aberfeldie,Suburb_Airport West,...,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
1,2,2.5,2.0,1.0,1.0,202.0,160.2564,4019.0,False,False,...,False,True,False,False,True,False,False,False,False,False
2,2,2.5,2.0,1.0,0.0,156.0,79.0000,4019.0,False,False,...,False,True,False,False,True,False,False,False,False,False
4,3,2.5,3.0,2.0,0.0,134.0,150.0000,4019.0,False,False,...,False,True,False,False,True,False,False,False,False,False
5,3,2.5,3.0,2.0,1.0,94.0,160.2564,4019.0,False,False,...,False,True,False,False,True,False,False,False,False,False
6,4,2.5,3.0,1.0,2.0,120.0,142.0000,4019.0,False,False,...,False,True,False,False,True,False,False,False,False,False

In [41]:
x.shape

(27244, 744)

In [87]:
# Split dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 2)

In [88]:
x_train.shape

(19070, 744)

In [89]:
x_test.shape

(8174, 744)

In [90]:
# Train model
from sklearn.linear_model import LinearRegression 
model = LinearRegression()

In [91]:
model.fit(x_train, y_train)

LinearRegression()

## Model Evaluation

The model is evaluated using standard regression metrics:

- R² Score: Measures how well the model explains the variance in the data  
- Mean Absolute Error (MAE): Measures the average prediction error  

These metrics help in understanding the accuracy and reliability of the model.

In [92]:
# Predictions
y_predict = model.predict(x_test)
y_predict

array([1672988.74423118, 1086049.72133639,  852828.79000837, ...,
        891754.56465992,  783898.88694562, 1170611.74698261],
      shape=(8174,))

In [93]:
## Evaluation metrics
model.intercept_

np.float64(636394.7291090852)

In [94]:
model.coef_

array([ 2.64001655e+05, -4.64732744e+04, -8.22349031e+04,  1.17151153e+05,
        4.29703140e+04,  2.35173742e+00,  4.70024530e+02,  4.92118905e+00,
        2.61342069e+05, -4.61008827e+04, -1.32312259e+05,  2.15453995e+05,
        1.20133839e+05,  2.72683980e+05,  1.74702166e+05, -8.00201053e+04,
       -1.50967673e+05, -4.94461444e+04,  1.17711126e+05, -1.28880253e+05,
       -3.49349656e+04, -8.54261329e+03,  6.19157896e+04, -2.57258028e+05,
       -1.10868116e+05, -2.42391674e+05,  1.79856957e+05, -1.22395100e+05,
        2.04625284e+05,  3.78258911e+04,  1.46681364e+05,  2.32198630e+03,
        7.35395731e+04, -5.29198410e+04,  1.90482393e+05, -3.20451670e+05,
        7.49515014e+04, -2.83019804e+04,  2.69103300e+04,  2.78824270e+05,
        1.51386730e+05, -1.06324212e+05, -8.45087700e+04,  2.96568248e+05,
        1.50644588e+05, -7.60424882e-07,  1.75999576e+05, -1.20057166e+05,
       -9.64544651e+03,  3.68377378e+05, -1.35478625e+05, -6.38092126e+04,
        3.53493139e+04,  1.12364756e+05,  1.50210824e+04,  3.80702958e+04,
       -2.07783976e+04,  5.60656190e-07, -2.80289620e+05,  3.62799617e+06,
       -1.70813150e+05,  4.34592162e+03, -2.42377714e+05, -3.46858959e+05,
       -5.38387981e+04, -5.68653064e+04, -1.25183575e+05,  7.32456333e+04,
       -1.49059860e+05,  5.81185670e+05,  1.46226853e+05,  3.17997075e+05,
       -4.57316260e+03, -2.55638831e+05,  3.69455304e+05, -1.15029553e+05,
       -2.11025506e+05,  8.21526909e+04,  2.36197162e+04,  2.12508573e+04,
       -5.82009613e+04,  3.49164828e+05, -4.06742065e+04, -2.43821088e+05,
       -2.12390672e+05, -3.73145696e+05,  1.86572073e+04, -2.25972697e+05,
        1.27539824e+05,  3.85986055e+05, -1.34115133e+05, -2.24490607e+05,
       -1.58738964e+05,  3.20740510e+04, -5.87051930e+04, -8.51778156e+04,
        1.43016150e+03,  1.84505150e+04, -5.84566147e+04, -6.55575568e+03,
       -2.39441933e+04,  5.22360613e+04, -6.13585217e+04,  4.67653420e+04,
        1.11906081e+05, -3.03524602e+05,  4.91638266e+04, -1.10861406e+05,
        9.87958629e-07,  5.25384277e+04, -6.48677726e+04, -4.42026057e+03,
       -1.63737753e+05, -1.16744031e+05,  2.08371325e+05, -1.92328642e+05,
       -4.19130496e+05, -2.27472230e+04,  1.94858270e+04,  1.13215212e+05,
       -2.32309284e+05, -9.15221377e+04,  3.91898843e+05,  3.71809224e+05,
        2.14264774e+05,  4.56828686e+04,  1.77559141e+04, -1.93905771e+05,
        3.66816256e+04,  3.38113878e+05, -2.79050352e+05, -8.29367251e+04,
        9.97135675e+04,  6.29461729e+04, -1.28958954e+04, -1.03659113e-06,
       -3.60378181e-07,  1.51675664e+05, -8.34519510e+04,  1.32289977e+05,
       -4.04193997e-07,  1.88968644e+05,  2.27651164e+05, -7.45096449e+04,
       -3.91229683e+04, -8.01720716e+04,  2.10537725e+05,  3.41965886e+03,
        4.31104649e+05, -1.41337601e+05,  3.58517423e+06,  3.58964287e+06,
       -2.33369616e+05, -2.08870436e+04, -7.74835945e+04,  2.62966427e+05,
       -7.85407926e+04, -1.62721244e+05,  6.40544210e+04,  3.09646400e+04,
       -1.20989873e+05,  8.61815063e+04,  1.73121003e+05, -2.27069888e+05,
       -2.58026614e+04, -2.67500635e+05, -1.32163855e+05,  7.82800590e+05,
       -1.24592191e+05,  4.38940519e+04, -1.00942551e+05, -3.11541673e+05,
       -4.44153152e+05, -1.21722020e+05, -3.36690866e+04, -1.64000640e+04,
        4.89990221e+04, -1.55566512e+05,  4.90631011e+04, -1.47225364e+04,
        4.28312699e+05, -1.49880671e+05,  2.32370587e+05, -1.49126738e+05,
        1.17089769e+05, -2.21276971e+04,  5.75378587e+04,  2.26855684e+05,
       -5.30691460e+04, -7.69823131e+04, -8.66406502e+04, -1.45452985e+05,
        4.79451757e+04,  9.64929441e+04, -3.73488957e+04, -7.47806909e+03,
        8.85013855e+04, -2.09808037e+04,  6.43567662e+04,  2.69324350e+05,
       -1.75802482e+05,  1.60203278e+05,  8.68965146e+03, -1.27725760e+05,
        4.32684775e+04,  9.52092704e+04,  1.42820815e+05,  7.56299670e+04,
       -6.66299661e+04,  4.12652219e+05, -2.37206273e+04, -1.69397975e+04,
        1.99998148e+05, -4.93913356e+04,  8.05303222e+03, -4.09129648e+04,
       -4.66189631e+03,  2.43831423e+05,  9.54077116e+04,  7.43722706e+04,
        6.84473453e+04,  5.45882056e+05, -1.66101989e+05,  1.00262668e+05,
       -2.44312782e+04,  1.07806494e+05, -2.64896940e+04, -3.30293442e+05,
        6.83588985e+04, -1.45828165e+05, -2.24756995e+05,  1.74303293e+05,
       -7.35196577e+04,  1.39208243e+05, -3.28319733e+04, -8.16548098e+03,
        8.29707192e+04, -1.70745894e+07, -4.93877616e+04,  5.62048104e+04,
       -4.64607964e+03, -2.94956617e+04,  4.33613194e+05,  1.50951595e+05,
        1.10255451e+05,  1.43455317e+04,  1.01343234e+05, -6.23746391e+02,
       -3.19540672e+04, -3.66958402e+05,  3.29968640e+04,  1.10537261e+05,
        8.45386941e+04,  2.24213986e+05,  3.02731380e+05, -3.73432326e+04,
        2.03679807e+05,  3.67140495e+05,  1.90774036e+05, -2.10308058e+05,
       -5.41525766e+04, -3.13521550e+05, -1.07316001e+05,  4.35657534e+05,
       -2.12983273e+05, -1.27317003e+05, -4.55798871e+03,  3.72013770e+06,
        4.28054514e+04,  9.13734826e+04, -6.29598262e+04, -1.22422551e+05,
        3.95900570e+05, -1.79171948e+05, -2.23235905e+05, -9.05652185e+04,
       -1.24989602e+05,  1.74799999e+05,  8.10324558e+04, -1.75102638e+05,
        1.87501424e+05,  6.43885732e+04,  5.78270941e+04,  2.16001414e+05,
       -3.82162193e+05, -6.48997658e+04, -1.28734627e+05, -1.10232449e+05,
       -9.96186648e+04, -3.99572192e+05, -7.05604302e+04, -3.08505777e+04,
        2.95247212e+04,  4.38872026e+04, -2.58987960e+05, -1.48687142e+05,
        8.53780738e+04, -1.61286396e+05,  4.70520152e+05,  4.30905486e+04,
       -6.68487513e+04, -1.57690339e+05,  2.91622053e+04,  1.16054180e+05,
       -5.36171763e+04, -1.91002039e+05, -4.08693867e+04, -3.53495125e-07,
        1.13483519e+05, -1.69881830e+05,  1.88296374e+05, -6.03018126e+04,
        5.43477940e+04,  7.22834127e+04,  2.18994627e+04, -6.60482469e+04,
        1.10944153e+05, -4.88384475e+04, -3.55271264e+04,  3.22133311e+04,
       -3.44950732e+05,  4.19717839e+05,  1.59891743e+05, -2.61106654e+05,
       -2.25289823e+05,  4.14927680e+05, -2.14622941e+05, -3.20620134e+04,
        7.75063095e+04, -7.25080114e+04, -3.16742535e+04, -1.67403490e+05,
       -8.77419827e+04, -5.89166674e+04,  4.88562011e+04, -8.08491868e+04,
       -1.62022300e+05,  4.65811303e+05,  4.10853539e+05, -1.71988925e+04,
        3.03450379e+05, -2.87535369e+03, -1.53891675e+05,  1.42659814e+05,
       -4.84645623e+03,  4.05389293e+05, -1.07916354e+05,  2.54322871e+05,
        3.84614603e+04, -3.64762625e+04, -3.85480430e+04, -2.74249921e+05,
       -4.78638143e+05,  7.13447079e+04,  3.70939160e+04,  3.26116000e+04,
        1.47147151e+04, -4.97983196e+04,  1.23665612e+05,  7.53123093e+05,
        1.76890126e+05,  1.24276266e-06,  5.14482663e+05,  1.14546661e+05,
       -9.80624456e+04, -1.38614089e+05, -1.66790347e+04, -1.12822691e+05,
        1.93670126e+05,  2.55161796e+05, -1.57484822e+05, -6.28092130e+04,
        1.22195660e+05, -1.12638254e+05,  1.70418827e+05, -1.44523794e+04,
        3.52010027e+05,  2.11671077e+05,  9.93172746e+04,  4.16123302e+05,
       -7.46423125e+04,  8.45852697e+04, -2.04922786e+03,  8.05677238e+04,
        2.74200916e+05,  1.09644553e+05,  5.26628759e+04,  5.87460818e-07,
        1.13230018e+05,  5.58626198e-07,  8.08024521e+04,  8.48022697e+05,
       -9.25356289e-07, -5.58390164e+05,  1.04744352e+05, -2.11658017e+05,
       -2.18050205e+04,  1.07178179e+05,  1.82990240e+05,  1.08785559e+05,
        5.89172551e+04,  1.70384474e+05,  1.56051829e-06, -9.54807526e+03,
        1.09721979e+05, -9.93742188e+04,  3.61972875e+05, -1.70170097e-07,
       -5.70535148e+04,  1.04347344e+05, -1.73015750e+05,  4.55491839e+05,
        1.40690247e+05,  1.85827957e-06,  1.80955698e+05,  4.93857123e+05,
        1.25502353e+05, -5.02929519e+05,  1.56920807e+05, -2.54761319e+05,
        1.76535211e+05, -2.09782291e+05,  1.47294579e+05,  2.08252507e+02,
        3.66287160e+05,  1.16352975e+05,  2.51706031e+05, -7.10891982e-07,
        2.68433601e+05,  1.58093671e+05,  2.57441813e+05, -5.04510783e+03,
       -1.71186390e+05, -3.18829112e+03,  9.43052822e+04,  9.44735937e+04,
        8.45489742e+04, -2.21451056e+04,  1.37543076e+06,  2.02918365e+05,
        7.18308189e+03,  1.32174741e+05, -4.91389112e+03,  5.90574928e-07,
       -1.93664878e+05, -7.61071440e+03, -3.18875869e+04,  9.05543135e+04,
        1.02563902e+05,  3.80185495e+05,  7.65580293e+04,  9.93937706e+04,
        1.18055239e+05,  9.55709321e+04,  1.14506299e+05,  9.12714275e+04,
       -1.13332948e+05, -7.39045077e+04,  6.67932909e-08,  7.42060365e-07,
        7.47584274e+04, -2.37603672e-07,  2.82127436e+04,  1.21433252e+05,
        1.18684248e+05, -3.29414442e+05, -6.75924753e+04,  3.26628034e+04,
       -3.92787005e+05, -9.83423504e+04, -5.50663590e+03,  1.20162572e+05,
        8.49129927e+04,  5.79639629e+05,  9.91517764e+04,  1.30448391e+06,
       -1.18859883e+05, -2.24228911e+05,  9.64116760e+04, -8.79272625e+04,
        6.85396694e+04, -3.14994882e+04,  5.30344055e+04,  1.41116158e+05,
        2.50683184e+05,  7.79003343e+03,  1.45634191e+06,  1.86064314e+05,
        1.31531000e+05, -6.38538040e-07,  8.92378614e+04,  4.07573503e+04,
        1.49188947e+04,  9.91561814e+04,  1.36653281e+05, -1.50699634e-07,
        1.49569360e+05,  1.17085568e+05,  1.71835072e+05,  1.78020014e+05,
        1.21915184e+05, -1.43905679e+05, -4.32528035e+05,  1.92102455e+05,
       -1.96934553e+05,  4.68488324e+04, -2.93513773e+05,  5.57081987e+05,
       -2.11469696e+05,  1.17235675e+05,  9.18429428e+05, -1.16674010e+04,
        1.26746730e+05, -7.53943094e+04,  7.89438422e+04, -1.82950078e+02,
        7.74044051e+05, -9.27483690e+04,  2.38338540e+05,  2.07516884e+05,
        2.51718322e+04,  1.33933903e+05,  2.75227231e+04,  2.87491295e+04,
        2.77899052e+05,  1.39467691e+05, -1.15425792e-07, -4.96560347e+05,
        9.59471875e+04,  3.57640140e+05, -1.84383805e+04,  1.06868600e+05,
       -3.57217064e+04, -1.53214223e+05, -5.27241787e+04,  1.02512919e+05,
        3.83446784e+05, -1.28239558e+05,  7.72616653e+04,  3.30670722e+05,
        1.80511050e+05, -8.26257747e-08,  1.23750972e+05, -1.49757037e+05,
       -2.75336788e-07,  1.58017786e+05, -3.48169124e-07,  7.18798629e+04,
       -6.09912947e+04,  2.11310239e+05,  1.97123976e+05,  6.90046026e+04,
        1.92850887e+05,  1.11405761e+05,  7.18641121e+05,  2.67202552e+05,
        1.20396076e+05, -1.81920829e+05,  1.11717868e+05,  1.46927396e+05,
        1.76073719e+05, -2.56586520e+04,  1.03744404e+05,  1.04372243e+05,
        2.75725026e+05,  8.87631475e+05, -1.40661349e+04,  4.28234464e+04,
        2.40476618e+05,  5.25669353e+04,  2.66547431e-07,  7.36308707e+04,
       -1.99177851e+05,  7.73502032e+04,  3.96904684e+05,  1.22746274e+05,
        1.25736135e+04,  1.02372881e+05, -4.62355767e+04, -5.72395032e+03,
       -5.81698603e+04, -1.77656602e+04,  2.56026397e-07, -1.49447249e+04,
        3.04713671e+05,  1.08773530e+05,  1.27825327e+05,  3.27363214e+05,
        3.01491136e+05,  3.22605797e+05,  4.23817624e+05,  2.38984595e+04,
        1.10893901e+05,  1.10833058e+05,  4.99224168e+04, -1.71246938e-07,
       -7.93661457e-08,  8.78265313e+04, -2.70844614e+04,  2.13634454e+05,
        4.94532287e-07, -3.09386431e+05,  1.74869189e+04,  1.82083979e+05,
        7.84253288e+04,  1.24359081e+05,  2.11054351e+04,  3.35096696e+05,
        8.94984408e+04,  8.20956293e+04, -5.56144010e+04,  6.04010160e+04,
        3.64450459e+04,  1.16211595e-07,  4.47627863e+05,  1.75597620e+05,
        1.01251403e+05,  1.34898188e+05,  7.90194943e+04,  8.39610064e+04,
        2.91736796e-07,  1.21505969e+05,  1.58757215e+05,  3.76753394e+04,
       -1.68165101e+05,  3.80750152e+05, -3.05349468e+05,  1.82053090e+05,
        1.22623995e+05,  2.17097847e+05, -2.20141374e-07,  1.91386789e-07,
       -4.15794812e+05,  6.37156712e+04, -1.02596291e+05, -1.02712201e+05,
        6.81575330e-08,  1.93156972e+05, -4.73810360e-08,  1.55298937e+06,
        1.21398440e+05,  1.03958882e-07, -4.23187912e+03, -7.48296109e+04,
        9.25055732e+04, -1.38243195e-08,  9.11296906e+04, -6.80629942e+03,
       -1.38716132e-08,  5.00408414e+05,  1.91503204e-08,  6.56807502e+04,
       -2.73937792e+04, -1.25520379e+04, -5.08471536e+05, -2.87263009e+04,
        1.79261296e+05,  1.39028865e+05, -5.61904998e+05, -4.94765118e-09,
        3.61198092e+05,  2.43832418e+05,  1.22216980e+04,  7.27595761e-12,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -2.10162309e+05,
        1.46042630e+05,  3.94558288e+04,  1.75865554e+05,  1.80934935e+05,
        6.56774151e+04,  0.00000000e+00,  1.08108392e+05, -4.81375842e+04,
       -8.80354052e+04,  3.64996443e+05,  5.22248384e+04,  6.52251781e+04,
        1.27802669e+05,  1.44424475e+05, -3.42064972e+04,  3.36774085e+04,
        8.43057920e+04, -1.44455922e+04, -2.45114659e+05,  8.96434739e+04,
        2.90705747e+04,  2.56370954e+05,  4.19635090e+04,  2.53727923e+05,
        2.89923960e+05,  0.00000000e+00,  1.64218522e+05,  0.00000000e+00,
        6.34959842e+05,  1.36601956e+05,  3.40256922e+05,  8.36021884e+04,
        0.00000000e+00,  0.00000000e+00,  1.74777311e+05,  1.90932861e+05,
       -1.11791365e+04,  4.57513423e+05,  3.42212920e+05, -1.52759812e+05,
        4.76269168e+05,  2.35751036e+05,  2.89422194e+04,  3.70585386e+05,
        1.43902269e+05, -1.97243398e+04, -4.25829580e+04, -3.71251895e+04,
        2.30153703e+05,  1.11152390e+05, -2.55163838e+06,  1.34732814e+05,
       -1.16876625e+05,  1.39810549e+05,  4.22122163e+04, -1.23209577e+04,
        4.19717839e+05,  7.65053785e+04,  6.42879529e+04,  1.79856957e+05,
       -3.82877635e+04,  2.56105949e+05,  1.21886580e+05,  3.29761347e+05,
        1.31991945e+05,  8.74679302e+04, -1.47280371e+05,  2.17770891e+04,
        2.12321402e+05,  2.23139975e+05, -2.16051847e+05, -8.03539773e+04,
        1.29462472e+05,  1.96957251e+04, -2.16808841e+05,  1.69631410e+05])

In [95]:
#training accuracy
model.score(x_train, y_train)*100

68.27792395792723

In [96]:
#testing Accuracy
model.score(x_test,y_test)*100

13.853683161586815

## Ridge Regression

In [97]:
from sklearn.linear_model import Ridge

In [98]:
ridge_reg= Ridge(alpha=50, max_iter=100,)
ridge_reg.fit(x_train, y_train)

Ridge(alpha=50, max_iter=100)

In [102]:
ridge_reg.score(x_train, y_train)*100

66.22376739684329

In [103]:
ridge_reg.score(x_test, y_test)*100

66.70848945194956

In [108]:
from sklearn.metrics import mean_squared_error,r2_score, mean_absolute_error

In [110]:
y_predicted = ridge_reg.predict(x_test)
y_predicted

array([1627362.97274832, 1040671.45389949,  905510.14874907, ...,
        931940.4305978 ,  800466.36204517, 1241927.30653571],
      shape=(8174,))

In [115]:
r2_score(y_test,y_predicted)*100

66.70848945194956

In [113]:
mean_squared_error(y_test,y_predicted)

132273414674.95786

In [114]:
mean_absolute_error(y_test,y_predicted)

236797.37116612244

## Lasso Regression

In [101]:
from sklearn.linear_model import Lasso

In [104]:
lasso_reg = Lasso(alpha=50, max_iter=100)
lasso_reg.fit(x_train, y_train)

C:\Users\ritus\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.329e+15, tolerance: 7.963e+11
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=50, max_iter=100)

In [106]:
lasso_reg.score(x_train, y_train)

0.6767356948457683

In [107]:
lasso_reg.score(x_test,y_test)

0.6637669697137103

In [ ]:
## 🚀Conclusion

The project successfully demonstrates how machine learning can be used to predict house prices based on property features.

Key takeaways:
- Area and location are major factors influencing price  
- Data cleaning and feature engineering significantly improve model performance  
- The model provides reasonably accurate predictions  

Future improvements:
- Use advanced models like Random Forest or XGBoost  
- Include more features for better accuracy